# Smart Quality Monitoring & Analytics System

This project visualizes manufacturing quality metrics through a Tableau dashboard powered by a dual-mode data pipeline. Users can operate in manual mode (CSV import) or automatic mode (Python-generated data).

### Import necessary libraries

In [16]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Loading CSV file

In [17]:
df_manufacturing = pd.read_csv('manufacturing-quality-control-dataset.csv')

### Data Cleaning and preprocessing

In [18]:
df_manufacturing

,batch_id,production_date,product_code,shift,operator_id,inspection_id,inspection_date,inspector_id,quality_score,defect_type,defect_severity,defect_count,rework_required,comments,factory_location
0,A1234-20240601,2024-06-01,PRD-02,afternoon,OP-5691,INSP-0001,2024-06-01T15:22:17,INS-2231,99.7,NaN,NaN,0,False,No issues detected. Batch meets all quality be...,Factory-E1
1,B0876-20240602,2024-06-02,PRD-03,morning,OP-1674,INSP-0002,2024-06-02T09:18:43,INS-9052,87.4,NaN,NaN,0,False,Perfect batch. No defects observed.,Factory-Y7
2,C4218-20240603,2024-06-03,PRD-01,night,OP-2517,INSP-0003,2024-06-04T00:43:11,INS-0342,81.1,scratch,1.0,1,False,Minor scratch detected but within tolerance.,Factory-Z3
3,D3127-20240603,2024-06-03,PRD-04,afternoon,OP-0033,INSP-0004,2024-06-03T16:08:29,INS-5961,94.3,NaN,NaN,0,False,Batch exceeded benchmarks.,Factory-X0
4,E2098-20240604,2024-06-04,PRD-02,morning,OP-5691,INSP-0005,2024-06-04T08:42:14,INS-9052,77.8,marking,2.0,2,False,Spot marking observed. No rework required.,Factory-G9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,T8452-20240624,2024-06-24,PRD-04,morning,OP-2186,INSP-0046,2024-06-24T08:55:00,INS-2517,97.5,NaN,NaN,0,False,No defects found during inspection.,Factory-Y7
196,U3917-20240624,2024-06-24,PRD-01,afternoon,OP-7777,INSP-0047,2024-06-24T15:23:00,INS-0112,76.9,dent,2.0,1,False,"Minor dent found, batch passes.",Factory-X0
197,V8093-20240625,2024-06-25,PRD-03,night,OP-1674,INSP-0048,2024-06-26T00:03:00,INS-3452,47.5,contamination,3.0,6,True,Batch failed due to contamination.,Factory-G9
198,W5076-20240625,2024-06-25,PRD-02,afternoon,OP-5691,INSP-0049,2024-06-25T14:57:00,INS-5648,98.2,NaN,NaN,0,False,Batch PRD-02 meets all benchmarks.,Factory-E1
199,X1834-20240626,2024-06-26,PRD-01,morning,OP-2517,INSP-0050,2024-06-26T11:13:00,INS-5691,100.0,NaN,NaN,0,False,"Exceptional batch, no defects.",Factory-A2

In [19]:
df_manufacturing.isnull().sum()

batch_id             0
production_date      0
product_code         0
shift                0
operator_id          0
inspection_id        0
inspection_date      0
inspector_id         0
quality_score        0
defect_type         89
defect_severity     89
defect_count         0
rework_required      0
comments             0
factory_location     0
dtype: int64

In [20]:
df_manufacturing.describe()

       quality_score  defect_severity  defect_count
count     200.000000       111.000000       200.000
mean       75.699400         2.612613         3.225
std        25.157249         1.113317         5.025
min         0.000000         1.000000         0.000
25%        63.600000         2.000000         0.000
50%        81.150000         3.000000         1.000
75%        96.225000         4.000000         5.000
max       100.000000         4.000000        20.000

In [21]:
df_manufacturing.duplicated().sum()

np.int64(0)

### EDA